version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: ocorrencia
      POSTGRES_DB: sistema-ocorrencia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Backend Java
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/meu_banco
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: senha
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - postgres

  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: